import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { Button } from "../components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "../components/ui/card";
import { Plus, Minus, Calculator as CalcIcon } from "lucide-react";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import { useLanguage } from "../context/LanguageContext";
import { calculatorTranslations } from "../translations/calculator";

interface FurnitureItem {
  id: number;
  category: string;
  name: string;
  volume: number;
  icon: string;
  quantity: number;
}

const Calculator = () => {
  const navigate = useNavigate();
  const { language } = useLanguage();
  const t = calculatorTranslations[language];

   const [items, setItems] = useState<FurnitureItem[]>([
  {
    id: 1,
    category: "salon",
    name: "Canapé 2 Pl",
    volume: 2,
    icon: "canape.png",
    quantity: 0,
  },
  {
    id: 2,
    category: "salon",
    name: "Canapé 3 Pl",
    volume: 2.5,
    icon: "canape-lit.png",
    quantity: 0,
  },
  {
    id: 3,
    category: "salon",
    name: "Canapé d'angle",
    volume: 3.5,
    icon: "canape (1).png",
    quantity: 0,
  },
  // Ajoutez les autres éléments ici avec leurs ID correspondants
  {
    id: 4,
    category: "salon",
    name: "Clic clac - Bz",
    volume: 2,
    icon: "canape (2).png",
    quantity: 0,
  },
  {
    id: 5,
    category: "salon",
    name: "Fauteuil",
    volume: 1,
    icon: "fauteuil.png",
    quantity: 0,
  },
  {
    id: 6,
    category: "salon",
    name: "Meuble living",
    volume: 2.5,
    icon: "meuble-tv 1.png",
    quantity: 0,
  },
  {
    id: 7,
    category: "salon",
    name: "Buffet bas (2 portes)",
    volume: 0.6,
    icon: "buffet (2).png",
    quantity: 0,
  },
  {
    id: 8,
    category: "salon",
    name: "Buffet bas (3 portes)",
    volume: 1.2,
    icon: "buffet 3.png",
    quantity: 0,
  },
  {
    id: 9,
    category: "salon",
    name: "Buffet bas ( 4 portes )",
    volume: 1.75,
    icon: "buffet (4).png",
    quantity: 0,
  },
  {
    id: 10,
    category: "salon",
    name: "Buffet 2 portes (bas + haut)",
    volume: 1.5,
    icon: "buffet (5).png",
    quantity: 0,
  },
  {
    id: 11,
    category: "salon",
    name: "Buffet 3 portes (bas + haut)",
    volume: 2,
    icon: "placard.png",
    quantity: 0,
  },
  {
    id: 12,
    category: "salon",
    name: "Buffet 4 portes (bas + haut)",
    volume: 2.5,
    icon: "buffet (7).png",
    quantity: 0,
  },
  {
    id: 13,
    category: "salon",
    name: "Vitrine - une porte",
    volume: 1,
    icon: "vitrine1.png",
    quantity: 0,
  },
  {
    id: 14,
    category: "salon",
    name: "Vitrine - deux portes",
    volume: 1.5,
    icon: "vitrine2.png",
    quantity: 0,
  },
  {
    id: 15,
    category: "salon",
    name: "Bibliothèque ouverte 40cm de large",
    volume: 0.5,
    icon: "bib1.png",
    quantity: 0,
  },
  {
    id: 16,
    category: "salon",
    name: "Bibliothèque ouverte 80cm de large",
    volume: 1,
    icon: "bib2.png",
    quantity: 0,
  },
  {
    id: 17,
    category: "salon",
    name: "Bibliothèque 4 portes / vitrine",
    volume: 1.5,
    icon: "bib3.png",
    quantity: 0,
  },
  {
    id: 18,
    category: "salon",
    name: "Table a manger 8 pers. Ou +",
    volume: 1.5,
    icon: "table8.png",
    quantity: 0,
  },
  {
    id: 19,
    category: "salon",
    name: "Table à manger 6 pers.",
    volume: 1,
    icon: "table6.png",
    quantity: 0,
  },
  {
    id: 20,
    category: "salon",
    name: "Table à manger 4 pers.",
    volume: 0.5,
    icon: "table4.png",
    quantity: 0,
  },
  {
    id: 21,
    category: "salon",
    name: "Chaise",
    volume: 0.25,
    icon: "chaise1.png",
    quantity: 0,
  },
  {
    id: 22,
    category: "salon",
    name: "Chaise pliante",
    volume: 0.1,
    icon: "chaise-pliante.png",
    quantity: 0,
  },
  {
    id: 23,
    category: "salon",
    name: "Chaise haute bébé",
    volume: 0.25,
    icon: "chaise-de-bebe.png",
    quantity: 0,
  },
  {
    id: 24,
    category: "salon",
    name: "Tabouret",
    volume: 0.1,
    icon: "tabouret.png",
    quantity: 0,
  },
  {
    id: 25,
    category: "salon",
    name: "Table basse",
    volume: 0.5,
    icon: "table-basse.png",
    quantity: 0,
  },
  {
    id: 26,
    category: "salon",
    name: "Meuble tv (petit)",
    volume: 0.5,
    icon: "table-tv.png",
    quantity: 0,
  },
  {
    id: 27,
    category: "salon",
    name: "Meuble tv (grand/complet)",
    volume: 1,
    icon: "meuble-tv grand.png",
    quantity: 0,
  },
  {
    id: 28,
    category: "salon",
    name: "Gueridon",
    volume: 0.25,
    icon: "gueridon.png",
    quantity: 0,
  },
  {
    id: 29,
    category: "salon",
    name: "Etagère colonne 80cm de large",
    volume: 1,
    icon: "etagere80.png",
    quantity: 0,
  },
  {
    id: 30,
    category: "salon",
    name: "Etagère colonne 40cm de large",
    volume: 0.5,
    icon: "etagere40.png",
    quantity: 0,
  },
  {
    id: 31,
    category: "salon",
    name: "Meuble divers (petits)",
    volume: 0.5,
    icon: "meuble salon petit.png",
    quantity: 0,
  },
  {
    id: 32,
    category: "salon",
    name: "Meuble divers (gros)",
    volume: 1,
    icon: "meuble salon grand.png",
    quantity: 0,
  },
  {
    id: 33,
    category: "salon",
    name: "TV PLASMA",
    volume: 0.25,
    icon: "TV PLASMA.png",
    quantity: 0,
  },
  {
    id: 34,
    category: "salon",
    name: "Lecteur dvd",
    volume: 0.1,
    icon: "lecteur-de-dvd.png",
    quantity: 0,
  },
  {
    id: 35,
    category: "salon",
    name: "Ensemble hifi",
    volume: 0.2,
    icon: "haut-parleurs.png",
    quantity: 0,
  },
  {
    id: 36,
    category: "salon",
    name: "Commode 3 tiroirs",
    volume: 0.5,
    icon: "commode3.png",
    quantity: 0,
  },
  {
    id: 37,
    category: "salon",
    name: "Commode 4 tiroirs",
    volume: 0.6,
    icon: "commode4.png",
    quantity: 0,
  },
  {
    id: 38,
    category: "salon",
    name: "Commode 5 tiroirs",
    volume: 0.7,
    icon: "commode5.png",
    quantity: 0,
  },
  {
    id: 39,
    category: "salon",
    name: "Secrétaire",
    volume: 1,
    icon: "lieu-de-travail.png",
    quantity: 0,
  },
  {
    id: 40,
    category: "salon",
    name: "Horloge Comtoise",
    volume: 0.3,
    icon: "lhorloge.png",
    quantity: 0,
  },
  {
    id: 41,
    category: "salon",
    name: "Selette",
    volume: 0.1,
    icon: "sellette.png",
    quantity: 0,
  },
  {
    id: 42,
    category: "salon",
    name: "Meuble chaussures",
    volume: 0.5,
    icon: "chaussure.png",
    quantity: 0,
  },
  {
    id: 43,
    category: "salon",
    name: "Miroir / tableau",
    volume: 0.1,
    icon: "miroir.png",
    quantity: 0,
  },
  {
    id: 44,
    category: "salon",
    name: "Miroir Psychée",
    volume: 0.25,
    icon: "miroir (1).png",
    quantity: 0,
  },
  {
    id: 45,
    category: "salon",
    name: "Lampe / Luminaire / Lustre",
    volume: 0.1,
    icon: "lustre.png",
    quantity: 0,
  },
  {
    id: 46,
    category: "salon",
    name: "Tableau / Cadre",
    volume: 0.02,
    icon: "cadre.png",
    quantity: 0,
  },
  {
    id: 47,
    category: "salon",
    name: "Tapis",
    volume: 0.1,
    icon: "tapis.png",
    quantity: 0,
  },
  {
    id: 48,
    category: "salon",
    name: "Lampadaire",
    volume: 0.2,
    icon: "lampadaire.png",
    quantity: 0,
  },
  {
    id: 49,
    category: "salon",
    name: "Cartons (grands) 54,5x34,5x30 cm",
    volume: 0.1,
    icon: "grand carton.png",
    quantity: 0,
  },
  {
    id: 50,
    category: "salon",
    name: "Cartons (petits) 34,5x27x30 cm",
    volume: 0.05,
    icon: "petit carton.png",
    quantity: 0,
  },
  {
    id: 51,
    category: "cuisine",
    name: "Table à manger 8 pers. Ou +",
    volume: 1.5,
    icon: "table8.png",
    quantity: 0,
  },
  {
    id: 52,
    category: "cuisine",
    name: "Table à manger 6 pers.",
    volume: 1,
    icon: "table6.png",
    quantity: 0,
  },
  {
    id: 53,
    category: "cuisine",
    name: "Table à manger 4 pers.",
    volume: 0.5,
    icon: "table4.png",
    quantity: 0,
  },
  {
    id: 54,
    category: "cuisine",
    name: "Table à manger pliante",
    volume: 0.35,
    icon: "table pliante.png",
    quantity: 0,
  },
  {
    id: 55,
    category: "cuisine",
    name: "Chaise",
    volume: 0.25,
    icon: "chaise1.png",
    quantity: 0,
  },
  {
    id: 56,
    category: "cuisine",
    name: "Chaise pliante",
    volume: 0.1,
    icon: "chaise pliante.png",
    quantity: 0,
  },
  {
    id: 57,
    category: "cuisine",
    name: "Chaise haute bébé",
    volume: 0.25,
    icon: "chaise-de-bebe.png",
    quantity: 0,
  },
  {
    id: 58,
    category: "cuisine",
    name: "Tabouret",
    volume: 0.1,
    icon: "tabouret (1).png",
    quantity: 0,
  },
  {
    id: 59,
    category: "cuisine",
    name: "Buffet bas (2 portes)",
    volume: 0.6,
    icon: "cuisine 2.png",
    quantity: 0,
  },
  {
    id: 60,
    category: "cuisine",
    name: "Buffet bas (3 portes)",
    volume: 1.2,
    icon: "cuisine 3.png",
    quantity: 0,
  },
  {
    id: 61,
    category: "cuisine",
    name: "Buffet bas ( 4 portes )",
    volume: 1.75,
    icon: "cuisine 4.png",
    quantity: 0,
  },
  {
    id: 62,
    category: "cuisine",
    name: "Buffet 2 portes (bas + haut)",
    volume: 1.5,
    icon: "buffet (3).png",
    quantity: 0,
  },
  {
    id: 63,
    category: "cuisine",
    name: "Buffet 3 portes (bas + haut)",
    volume: 2,
    icon: "buffet (6).png",
    quantity: 0,
  },
  {
    id: 64,
    category: "cuisine",
    name: "Buffet 4 portes (bas + haut)",
    volume: 2.5,
    icon: "buffet (7).png",
    quantity: 0,
  },
  {
    id: 65,
    category: "cuisine",
    name: "Confiturier",
    volume: 0.5,
    icon: "confiturier.png",
    quantity: 0,
  },
  {
    id: 66,
    category: "cuisine",
    name: "Desserte",
    volume: 0.25,
    icon: "desserte.png",
    quantity: 0,
  },
  {
    id: 67,
    category: "cuisine",
    name: "Elément bas",
    volume: 0.6,
    icon: "element bas.png",
    quantity: 0,
  },
  {
    id: 68,
    category: "cuisine",
    name: "Elément haut",
    volume: 0.5,
    icon: "cuisine haut.png",
    quantity: 0,
  },
  {
    id: 69,
    category: "cuisine",
    name: "Lampe / Luminaire",
    volume: 0.1,
    icon: "luminaire.png",
    quantity: 0,
  },
  {
    id: 70,
    category: "cuisine",
    name: "Poubelle",
    volume: 0.1,
    icon: "poubelle.png",
    quantity: 0,
  },
  {
    id: 71,
    category: "cuisine",
    name: "Rack / Casier à bouteilles",
    volume: 0.25,
    icon: "bouteilles-de-vin.png",
    quantity: 0,
  },
  {
    id: 72,
    category: "cuisine",
    name: "Petits meubles divers",
    volume: 0.5,
    icon: "cuisine petit.png",
    quantity: 0,
  },
  {
    id: 73,
    category: "cuisine",
    name: "Gros meubles divers",
    volume: 1,
    icon: "cuisine gros.png",
    quantity: 0,
  },
  {
    id: 74,
    category: "cuisine",
    name: "Cartons (grands) 54,5x34,5x30 cm",
    volume: 0.1,
    icon: "grand carton.png",
    quantity: 0,
  },
  {
    id: 75,
    category: "cuisine",
    name: "Cartons (petits) 34,5x27x30 cm",
    volume: 0.05,
    icon: "petit carton.png",
    quantity: 0,
  },
  {
    id: 76,
    category: "electromenagers",
    name: "Min iFrigo Tip Top",
    volume: 0.5,
    icon: "mini frigo.png",
    quantity: 0,
  },
  {
    id: 77,
    category: "electromenagers",
    name: "Réfrigérateur Standard",
    volume: 1,
    icon: "refrigerateur1.png",
    quantity: 0,
  },
  {
    id: 78,
    category: "electromenagers",
    name: "Réfrigérateur Combine",
    volume: 1.2,
    icon: "refrigerateur2.png",
    quantity: 0,
  },
  {
    id: 79,
    category: "electromenagers",
    name: "Refrigerateur 2 portes",
    volume: 1.5,
    icon: "refrigerateur3.png",
    quantity: 0,
  },
  {
    id: 80,
    category: "electromenagers",
    name: "Réfrigérateur Américain",
    volume: 2,
    icon: "refrigerateur4.png",
    quantity: 0,
  },
  {
    id: 81,
    category: "electromenagers",
    name: "Congelateur",
    volume: 1,
    icon: "congelateur.png",
    quantity: 0,
  },
  {
    id: 82,
    category: "electromenagers",
    name: "Four encastrable",
    volume: 0.4,
    icon: "four encastrable.png",
    quantity: 0,
  },
  {
    id: 83,
    category: "electromenagers",
    name: "Piano de cuisson",
    volume: 0.5,
    icon: "plaque.png",
    quantity: 0,
  },
  {
    id: 84,
    category: "electromenagers",
    name: "Four",
    volume: 0.5,
    icon: "four.png",
    quantity: 0,
  },
  {
    id: 85,
    category: "electromenagers",
    name: "Mini four",
    volume: 0.25,
    icon: "mini four.png",
    quantity: 0,
  },
  {
    id: 86,
    category: "electromenagers",
    name: "Gaziniere",
    volume: 0.5,
    icon: "le-fourneau (1).png",
    quantity: 0,
  },
  {
    id: 87,
    category: "electromenagers",
    name: "Plaque de cuisson",
    volume: 0.2,
    icon: "le-fourneau.png",
    quantity: 0,
  },
  {
    id: 88,
    category: "electromenagers",
    name: "Lave vaisselle",
    volume: 0.5,
    icon: "lave-vaisselle.png",
    quantity: 0,
  },
  {
    id: 89,
    category: "electromenagers",
    name: "Lave linge",
    volume: 0.5,
    icon: "machine-a-laver.png",
    quantity: 0,
  },
  {
    id: 90,
    category: "electromenagers",
    name: "Seche linge",
    volume: 0.5,
    icon: "seche-linge.png",
    quantity: 0,
  },
  {
    id: 91,
    category: "electromenagers",
    name: "Cave a vin (petite)",
    volume: 0.5,
    icon: "refroidisseur-de-vin.png",
    quantity: 0,
  },
  {
    id: 92,
    category: "electromenagers",
    name: "Cave a vin (grande)",
    volume: 1,
    icon: "du-vin grand.png",
    quantity: 0,
  },
  {
    id: 93,
    category: "electromenagers",
    name: "Micro-ondes",
    volume: 0.25,
    icon: "micro-onde.png",
    quantity: 0,
  },
  {
    id: 94,
    category: "electromenagers",
    name: "Petit Electromenager",
    volume: 0.1,
    icon: "petit-electromenager.png",
    quantity: 0,
  },
  {
    id: 95,
    category: "electromenagers",
    name: "Radiateur Electrique",
    volume: 0.15,
    icon: "radiateur.png",
    quantity: 0,
  },
  {
    id: 96,
    category: "electromenagers",
    name: "Climatiseur mobile",
    volume: 0.2,
    icon: "climatiseur.png",
    quantity: 0,
  },
  {
    id: 97,
    category: "electromenagers",
    name: "Chauffage mobile",
    volume: 0.2,
    icon: "chauffage-a-gaz.png",
    quantity: 0,
  },
  {
    id: 98,
    category: "electromenagers",
    name: "Machine à coudre",
    volume: 0.1,
    icon: "machine-a-coudre.png",
    quantity: 0,
  },
  {
    id: 99,
    category: "salle_de_bain",
    name: "Bac à linge",
    volume: 0.1,
    icon: "Bac à linge.png",
    quantity: 0,
  },

  {
    id: 100,
    category: "salle_de_bain",
    name: "Etendoir à linge (tancarville)",
    volume: 0.02,
    icon: "corde-a-linge.png",
    quantity: 0,
  },
  {
    id: 101,
    category: "salle_de_bain",
    name: "Lampe / Luminaire",
    volume: 0.1,
    icon: "ampoule.png",
    quantity: 0,
  },
  {
    id: 102,
    category: "salle_de_bain",
    name: "Meuble colonne",
    volume: 0.5,
    icon: "meuble colonne.png",
    quantity: 0,
  },
  {
    id: 103,
    category: "salle_de_bain",
    name: "Meuble bas  (2 portes)",
    volume: 0.6,
    icon: "salle-de-bains bas.png",
    quantity: 0,
  },
  {
    id: 104,
    category: "salle_de_bain",
    name: "Meuble haut (2 portes)",
    volume: 0.5,
    icon: "meuble bain haut.png",
    quantity: 0,
  },
  {
    id: 105,
    category: "salle_de_bain",
    name: "Meuble pharmacie",
    volume: 0.25,
    icon: "pharmacie.png",
    quantity: 0,
  },
  {
    id: 106,
    category: "salle_de_bain",
    name: "Miroir",
    volume: 0.1,
    icon: "miroir bain.png",
    quantity: 0,
  },
  {
    id: 107,
    category: "salle_de_bain",
    name: "Poubelle",
    volume: 0.05,
    icon: "seau.png",
    quantity: 0,
  },
  {
    id: 108,
    category: "salle_de_bain",
    name: "Table a langer",
    volume: 0.75,
    icon: "table-a-langer.png",
    quantity: 0,
  },
  {
    id: 109,
    category: "salle_de_bain",
    name: "Aspirateur",
    volume: 0.2,
    icon: "aspirateur.png",
    quantity: 0,
  },
  {
    id: 110,
    category: "salle_de_bain",
    name: "Balai",
    volume: 0.02,
    icon: "balais.png",
    quantity: 0,
  },
  {
    id: 111,
    category: "salle_de_bain",
    name: "Table à repasser (+ fer)",
    volume: 0.1,
    icon: "planche-a-repasser.png",
    quantity: 0,
  },
  {
    id: 112,
    category: "salle_de_bain",
    name: "Cartons (grands) 54,5x34,5x30 cm",
    volume: 0.1,
    icon: "grand carton.png",
    quantity: 0,
  },
  {
    id: 113,
    category: "salle_de_bain",
    name: "Cartons (petits) 34,5x27x30 cm",
    volume: 0.05,
    icon: "petit carton.png",
    quantity: 0,
  },
  {
    id: 114,
    category: "instruments",
    name: "Piano droit",
    volume: 2,
    icon: "piano1.png",
    quantity: 0,
  },
  {
    id: 115,
    category: "instruments",
    name: "Piano a queue",
    volume: 3,
    icon: "piano2.png",
    quantity: 0,
  },
  {
    id: 116,
    category: "instruments",
    name: "Violoncel, Violon, Guitare",
    volume: 0.1,
    icon: "musique.png",
    quantity: 0,
  },
  {
    id: 117,
    category: "instruments",
    name: "Batterie",
    volume: 2,
    icon: "batterie.png",
    quantity: 0,
  },
  {
    id: 118,
    category: "instruments",
    name: "Synthétiseur",
    volume: 0.5,
    icon: "clavier.png",
    quantity: 0,
  },
  {
    id: 119,
    category: "instruments",
    name: "Harpe",
    volume: 0.3,
    icon: "harpe.png",
    quantity: 0,
  },
  {
    id: 120,
    category: "instruments",
    name: "Trompette",
    volume: 0.1,
    icon: "le-jazz.png",
    quantity: 0,
  },
  {
    id: 121,
    category: "vegeteaux_et_animaux",
    name: "Plante / arbuste (H > 2m)",
    volume: 1.75,
    icon: "plante-en-croissance.png",
    quantity: 0,
  },
  {
    id: 122,
    category: "vegeteaux_et_animaux",
    name: "Plante grande taille (H < 2m)",
    volume: 1.5,
    icon: "plante.png",
    quantity: 0,
  },
  {
    id: 123,
    category: "vegeteaux_et_animaux",
    name: "Plante moyenne taille (H < 1m)",
    volume: 0.75,
    icon: "plante-en-croissance (2).png",
    quantity: 0,
  },
  {
    id: 124,
    category: "vegeteaux_et_animaux",
    name: "Plante petite taille (H < 50cm)",
    volume: 0.25,
    icon: "plante-en-croissance (1).png",
    quantity: 0,
  },
  {
    id: 125,
    category: "vegeteaux_et_animaux",
    name: "Plante deco",
    volume: 0.01,
    icon: "deco.png",
    quantity: 0,
  },
  {
    id: 126,
    category: "vegeteaux_et_animaux",
    name: "Pots de fleurs vides",
    volume: 0.1,
    icon: "pot-de-fleur.png",
    quantity: 0,
  },
  {
    id: 127,
    category: "vegeteaux_et_animaux",
    name: "Panier pour chien",
    volume: 0.15,
    icon: "cage-pour-chien.png",
    quantity: 0,
  },
  {
    id: 128,
    category: "vegeteaux_et_animaux",
    name: "Arbre a chat",
    volume: 0.1,
    icon: "jouet-pour-chat.png",
    quantity: 0,
  },
  {
    id: 129,
    category: "vegeteaux_et_animaux",
    name: "Aquarium  (vide)",
    volume: 2,
    icon: "aquarium.png",
    quantity: 0,
  },

  {
    id: 130,
    category: "chambre_bureau",
    name: "Sommier seul",
    volume: 0.5,
    icon: "sommier.png",
    quantity: 0,
  },
  {
    id: 131,
    category: "chambre_bureau",
    name: "Matelas seul",
    volume: 0.5,
    icon: "matelas.png",
    quantity: 0,
  },
  {
    id: 132,
    category: "chambre_bureau",
    name: "Parure de lit (couette + coussins)",
    volume: 0.15,
    icon: "couverture.png",
    quantity: 0,
  },
  {
    id: 133,
    category: "chambre_bureau",
    name: "Lit une place complet",
    volume: 1,
    icon: "lit-simple.png",
    quantity: 0,
  },
  {
    id: 134,
    category: "chambre_bureau",
    name: "Lit 2 places complet 140",
    volume: 1.5,
    icon: "lit140.png",
    quantity: 0,
  },
  {
    id: 135,
    category: "chambre_bureau",
    name: "Lit 2 places complet 160",
    volume: 2,
    icon: "lit160.png",
    quantity: 0,
  },
  {
    id: 136,
    category: "chambre_bureau",
    name: "Lit 2 places complet 180 ou +",
    volume: 2.5,
    icon: "lit180.png",
    quantity: 0,
  },
  {
    id: 137,
    category: "chambre_bureau",
    name: "Lit pont",
    volume: 3,
    icon: "lit pont.png",
    quantity: 0,
  },
  {
    id: 138,
    category: "chambre_bureau",
    name: "Lits superposés",
    volume: 2,
    icon: "lit-superpose.png",
    quantity: 0,
  },
  {
    id: 139,
    category: "chambre_bureau",
    name: "Lit bébé",
    volume: 0.5,
    icon: "chambre-de-bebe.png",
    quantity: 0,
  },
  {
    id: 140,
    category: "chambre_bureau",
    name: "Lit parapluie (pliable)",
    volume: 0.1,
    icon: "lit pliable.png",
    quantity: 0,
  },
  {
    id: 141,
    category: "chambre_bureau",
    name: "Table de chevet",
    volume: 0.25,
    icon: "la-table-de-nuit.png",
    quantity: 0,
  },
  {
    id: 142,
    category: "chambre_bureau",
    name: "Clic clac",
    volume: 2,
    icon: "clic clac.png",
    quantity: 0,
  },
  {
    id: 143,
    category: "chambre_bureau",
    name: "Commode 3 tiroirs",
    volume: 0.5,
    icon: "commode (3).png",
    quantity: 0,
  },
  {
    id: 144,
    category: "chambre_bureau",
    name: "Commode 4 tiroirs",
    volume: 0.6,
    icon: "commode (4).png",
    quantity: 0,
  },
  {
    id: 145,
    category: "chambre_bureau",
    name: "Commode 5 tiroirs",
    volume: 0.7,
    icon: "commode (5).png",
    quantity: 0,
  },
  {
    id: 146,
    category: "chambre_bureau",
    name: "Armoire 1 porte type ikea",
    volume: 1,
    icon: "armoire1.png",
    quantity: 0,
  },
  {
    id: 147,
    category: "chambre_bureau",
    name: "Armoire 1 porte type normande",
    volume: 1.5,
    icon: "armoire2.png",
    quantity: 0,
  },
  {
    id: 148,
    category: "chambre_bureau",
    name: "Armoire 2 portes type Ikea",
    volume: 1.5,
    icon: "armoire3.png",
    quantity: 0,
  },
  {
    id: 149,
    category: "chambre_bureau",
    name: "Armoire 2 portes coulissantes",
    volume: 2,
    icon: "2coulissante.png",
    quantity: 0,
  },
  {
    id: 150,
    category: "chambre_bureau",
    name: "Armoire 3 portes",
    volume: 2.5,
    icon: "3portes.png",
    quantity: 0,
  },
  {
    id: 151,
    category: "chambre_bureau",
    name: "Armoire 3 portes coulissantes",
    volume: 3,
    icon: "3portes.png",
    quantity: 0,
  },
  {
    id: 152,
    category: "chambre_bureau",
    name: "Armoire 4 portes",
    volume: 3,
    icon: "4portes.png",
    quantity: 0,
  },
  {
    id: 153,
    category: "chambre_bureau",
    name: "Armoire 4 portes coulissantes",
    volume: 4,
    icon: "4portes.png",
    quantity: 0,
  },
  {
    id: 154,
    category: "chambre_bureau",
    name: "Coiffeuse",
    volume: 0.5,
    icon: "coiffeuse.png",
    quantity: 0,
  },
  {
    id: 155,
    category: "chambre_bureau",
    name: "Etagère colonne 80cm de large",
    volume: 1,
    icon: "etagere 80.png",
    quantity: 0,
  },
  {
    id: 156,
    category: "chambre_bureau",
    name: "Etagère colonne 40cm de large",
    volume: 0.5,
    icon: "etagere 40.png",
    quantity: 0,
  },
  {
    id: 157,
    category: "chambre_bureau",
    name: "Meuble TV (petit / bas)",
    volume: 0.5,
    icon: "meuble-tv.png",
    quantity: 0,
  },
  {
    id: 158,
    category: "chambre_bureau",
    name: "Meuble TV (complet / grand)",
    volume: 1,
    icon: "meuble-tv grand.png",
    quantity: 0,
  },
  {
    id: 159,
    category: "chambre_bureau",
    name: "Portant à Roulettes",
    volume: 0.25,
    icon: "portant.png",
    quantity: 0,
  },
  {
    id: 160,
    category: "chambre_bureau",
    name: "Bureau (petit)",
    volume: 0.5,
    icon: "bureau1.png",
    quantity: 0,
  },
  {
    id: 161,
    category: "chambre_bureau",
    name: "Bureau (grand)",
    volume: 1,
    icon: "bureau2.png",
    quantity: 0,
  },
  {
    id: 162,
    category: "chambre_bureau",
    name: "Chaise",
    volume: 0.25,
    icon: "chaise.png",
    quantity: 0,
  },
  {
    id: 163,
    category: "chambre_bureau",
    name: "Fauteuil bureau",
    volume: 0.35,
    icon: "chaise-de-bureau.png",
    quantity: 0,
  },
  {
    id: 164,
    category: "chambre_bureau",
    name: "Fauteuil Relax",
    volume: 1,
    icon: "se-detendre.png",
    quantity: 0,
  },
  {
    id: 165,
    category: "chambre_bureau",
    name: "Meuble informatique",
    volume: 0.5,
    icon: "meuble info.png",
    quantity: 0,
  },
  {
    id: 166,
    category: "chambre_bureau",
    name: "Ecran et tour pc",
    volume: 0.25,
    icon: "tour-pc-et-moniteur.png",
    quantity: 0,
  },
  {
    id: 167,
    category: "chambre_bureau",
    name: "Imprimante",
    volume: 0.2,
    icon: "imprimante.png",
    quantity: 0,
  },
  {
    id: 168,
    category: "chambre_bureau",
    name: "Imprimante (pro)",
    volume: 0.5,
    icon: "imprimante-multifonction.png",
    quantity: 0,
  },
  {
    id: 169,
    category: "chambre_bureau",
    name: "Cubes plastique",
    volume: 0.2,
    icon: "cube.png",
    quantity: 0,
  },
  {
    id: 170,
    category: "chambre_bureau",
    name: "Televiseur",
    volume: 0.25,
    icon: "moniteur.png",
    quantity: 0,
  },
  {
    id: 171,
    category: "chambre_bureau",
    name: "Miroir / tableau",
    volume: 0.1,
    icon: "miroir.png",
    quantity: 0,
  },
  {
    id: 172,
    category: "chambre_bureau",
    name: "Miroir Psychée",
    volume: 0.25,
    icon: "miroir (1).png",
    quantity: 0,
  },
  {
    id: 173,
    category: "chambre_bureau",
    name: "Lampe / Luminaire / Lustre",
    volume: 0.1,
    icon: "ampoule.png",
    quantity: 0,
  },
  {
    id: 174,
    category: "chambre_bureau",
    name: "Tableau / Cadre",
    volume: 0.02,
    icon: "cadre.png",
    quantity: 0,
  },
  {
    id: 175,
    category: "chambre_bureau",
    name: "Tapis",
    volume: 0.1,
    icon: "tapis.png",
    quantity: 0,
  },
  {
    id: 176,
    category: "chambre_bureau",
    name: "Lampadaire",
    volume: 0.2,
    icon: "lampadaire.png",
    quantity: 0,
  },
  {
    id: 177,
    category: "chambre_bureau",
    name: "Ventilateur",
    volume: 0.1,
    icon: "ventilateur.png",
    quantity: 0,
  },
  {
    id: 178,
    category: "chambre_bureau",
    name: "Voiture/Tract. Enfant. (grd modèle)",
    volume: 0.5,
    icon: "petite-voiture.png",
    quantity: 0,
  },
  {
    id: 179,
    category: "chambre_bureau",
    name: "Meuble divers (petits)",
    volume: 0.5,
    icon: "chambre.png",
    quantity: 0,
  },
  {
    id: 180,
    category: "chambre_bureau",
    name: "Meuble divers (gros)",
    volume: 1,
    icon: "chambre (1).png",
    quantity: 0,
  },
  {
    id: 181,
    category: "chambre_bureau",
    name: "Cartons (grands) 54,5x34,5x30 cm",
    volume: 0.1,
    icon: "grand carton.png",
    quantity: 0,
  },
  {
    id: 182,
    category: "chambre_bureau",
    name: "Cartons (petits) 34,5x27x30 cm",
    volume: 0.05,
    icon: "petit carton.png",
    quantity: 0,
  },
  {
    id: 183,
    category: "sports_et_loisir",
    name: "Appareil musculation",
    volume: 1,
    icon: "appareil-de-musculation.png",
    quantity: 0,
  },
  {
    id: 184,
    category: "sports_et_loisir",
    name: "Tapis cours",
    volume: 1,
    icon: "tapis-roulant.png",
    quantity: 0,
  },
  {
    id: 185,
    category: "sports_et_loisir",
    name: "Vélo d'apartement",
    volume: 2,
    icon: "velo-stationnaire.png",
    quantity: 0,
  },
  {
    id: 186,
    category: "sports_et_loisir",
    name: "Rameur",
    volume: 3,
    icon: "aviron.png",
    quantity: 0,
  },
  {
    id: 187,
    category: "sports_et_loisir",
    name: "Petit trampoline",
    volume: 0.5,
    icon: "trampoline.png",
    quantity: 0,
  },
  {
    id: 188,
    category: "sports_et_loisir",
    name: "Grand Trampoline",
    volume: 1.5,
    icon: "trampoline (1).png",
    quantity: 0,
  },
  {
    id: 189,
    category: "sports_et_loisir",
    name: "Baby foot",
    volume: 0.5,
    icon: "baby-foot.png",
    quantity: 0,
  },
  {
    id: 190,
    category: "sports_et_loisir",
    name: "Billard",
    volume: 2,
    icon: "table-de-billard.png",
    quantity: 0,
  },
  {
    id: 191,
    category: "sports_et_loisir",
    name: "Table de Ping pong",
    volume: 1.5,
    icon: "table-de-ping-pong.png",
    quantity: 0,
  },
  {
    id: 192,
    category: "sports_et_loisir",
    name: "Cage de foot (démontée)",
    volume: 0.8,
    icon: "but-de-foot.png",
    quantity: 0,
  },
  {
    id: 193,
    category: "sports_et_loisir",
    name: "Panier de basket (démonté)",
    volume: 0.25,
    icon: "basketball.png",
    quantity: 0,
  },
  {
    id: 194,
    category: "sports_et_loisir",
    name: "Planche à voile",
    volume: 0.5,
    icon: "voile.png",
    quantity: 0,
  },
  {
    id: 195,
    category: "sports_et_loisir",
    name: "Sac de golf",
    volume: 0.15,
    icon: "sac-de-golf.png",
    quantity: 0,
  },
  {
    id: 196,
    category: "sports_et_loisir",
    name: "Skis (nombre de paires)",
    volume: 0.04,
    icon: "skieur (1).png",
    quantity: 0,
  },
  {
    id: 197,
    category: "sports_et_loisir",
    name: "Trotinette / Skate board",
    volume: 0.1,
    icon: "trottinette.png",
    quantity: 0,
  },
  {
    id: 198,
    category: "sports_et_loisir",
    name: "Vtt, vélo ville",
    volume: 0.7,
    icon: "velo-de-montagne.png",
    quantity: 0,
  },
  {
    id: 199,
    category: "sports_et_loisir",
    name: "Planche",
    volume: 0.2,
    icon: "le-surf.png",
    quantity: 0,
  },
  {
    id: 200,
    category: "sports_et_loisir",
    name: "Voiturette enfant",
    volume: 0.5,
    icon: "voiturette-de-golf.png",
    quantity: 0,
  },
  {
    id: 201,
    category: "sports_et_loisir",
    name: "Cabanon /  Maison d'enfant",
    volume: 3,
    icon: "cabanon.png",
    quantity: 0,
  },
  {
    id: 202,
    category: "sports_et_loisir",
    name: "Balançoire",
    volume: 2,
    icon: "oscillations.png",
    quantity: 0,
  },
  {
    id: 203,
    category: "sports_et_loisir",
    name: "Bac à sable enfant",
    volume: 0.5,
    icon: "bac-a-sable.png",
    quantity: 0,
  },
  {
    id: 204,
    category: "vehicule_et_accessoires",
    name: "Voiture",
    volume: 12,
    icon: "auto.png",
    quantity: 0,
  },
  {
    id: 205,
    category: "vehicule_et_accessoires",
    name: "Scooter",
    volume: 2,
    icon: "scooter.png",
    quantity: 0,
  },
  {
    id: 206,
    category: "vehicule_et_accessoires",
    name: "Moto",
    volume: 3,
    icon: "moto.png",
    quantity: 0,
  },
  {
    id: 207,
    category: "vehicule_et_accessoires",
    name: "Quad",
    volume: 2,
    icon: "quad.png",
    quantity: 0,
  },
  {
    id: 208,
    category: "vehicule_et_accessoires",
    name: "Motoculteur",
    volume: 2,
    icon: "machine.png",
    quantity: 0,
  },
  {
    id: 209,
    category: "vehicule_et_accessoires",
    name: "Kart",
    volume: 1,
    icon: "faire-du-kart.png",
    quantity: 0,
  },
  {
    id: 210,
    category: "vehicule_et_accessoires",
    name: "Coffre de toit",
    volume: 0.5,
    icon: "galerie-de-toit.png",
    quantity: 0,
  },
  {
    id: 211,
    category: "vehicule_et_accessoires",
    name: "Pneu",
    volume: 0.25,
    icon: "pneu.png",
    quantity: 0,
  },
  {
    id: 212,
    category: "vehicule_et_accessoires",
    name: "Poussette / Siège auto",
    volume: 0.35,
    icon: "poussette-de-bebe.png",
    quantity: 0,
  },
  {
    id: 213,
    category: "vehicule_et_accessoires",
    name: "Maxi cosy",
    volume: 0.05,
    icon: "porte-bebe.png",
    quantity: 0,
  },
  {
    id: 214,
    category: "vehicule_et_accessoires",
    name: "Valise",
    volume: 0.1,
    icon: "les-valises.png",
    quantity: 0,
  },
  {
    id: 215,
    category: "vehicule_et_accessoires",
    name: "Coffre",
    volume: 0.5,
    icon: "coffre-fort.png",
    quantity: 0,
  },
  {
    id: 216,
    category: "vehicule_et_accessoires",
    name: "Parabole (décrochée du toit)",
    volume: 0.1,
    icon: "antenne-satellite.png",
    quantity: 0,
  },
  {
    id: 217,
    category: "materiel_bricolage",
    name: "Tondeuse",
    volume: 1,
    icon: "tondeuse-a-gazon.png",
    quantity: 0,
  },
  {
    id: 218,
    category: "materiel_bricolage",
    name: "Tondeuse autoporté",
    volume: 0.25,
    icon: "tondeuse-a-gazon (1).png",
    quantity: 0,
  },
  {
    id: 219,
    category: "materiel_bricolage",
    name: "Lot outils de jardin / ratelier",
    volume: 0.3,
    icon: "boite-a-outils.png",
    quantity: 0,
  },
  {
    id: 220,
    category: "materiel_bricolage",
    name: "Nettoyeur pression",
    volume: 0.2,
    icon: "nettoyeur-haute-pression.png",
    quantity: 0,
  },
  {
    id: 221,
    category: "materiel_bricolage",
    name: "Tuyau d'arrosage + enrouleur",
    volume: 0.25,
    icon: "tuyau-deau.png",
    quantity: 0,
  },
  {
    id: 222,
    category: "materiel_bricolage",
    name: "GROS MATERIEL BRICOLAGE",
    volume: 1.5,
    icon: "outils-agricoles.png",
    quantity: 0,
  },
  {
    id: 223,
    category: "materiel_bricolage",
    name: "Etabli",
    volume: 1,
    icon: "etabli.png",
    quantity: 0,
  },
  {
    id: 224,
    category: "materiel_bricolage",
    name: "Brouette",
    volume: 1,
    icon: "brouette.png",
    quantity: 0,
  },
  {
    id: 225,
    category: "materiel_bricolage",
    name: "Echelle, escabeau",
    volume: 0.2,
    icon: "echelle.png",
    quantity: 0,
  },
  {
    id: 226,
    category: "materiel_bricolage",
    name: "Tréteaux",
    volume: 0.02,
    icon: "tretaux.png",
    quantity: 0,
  },
  {
    id: 227,
    category: "materiel_bricolage",
    name: "Cantine",
    volume: 0.3,
    icon: "cantine.png",
    quantity: 0,
  },
  {
    id: 228,
    category: "materiel_bricolage",
    name: "Diable",
    volume: 0.1,
    icon: "diable.png",
    quantity: 0,
  },
  {
    id: 229,
    category: "materiel_bricolage",
    name: "Etagère démontable",
    volume: 0.5,
    icon: "etageres.png",
    quantity: 0,
  },
  {
    id: 230,
    category: "materiel_bricolage",
    name: "Malle",
    volume: 0.5,
    icon: "bagage (1).png",
    quantity: 0,
  },
  {
    id: 231,
    category: "materiel_bricolage",
    name: "Planche vrac",
    volume: 0.2,
    icon: "bois.png",
    quantity: 0,
  },
  {
    id: 232,
    category: "materiel_bricolage",
    name: "Meubles divers gros",
    volume: 1,
    icon: "meubles_gros.png",
    quantity: 0,
  },
  {
    id: 233,
    category: "materiel_bricolage",
    name: "Cartons (grands) 54,5x34,5x30 cm",
    volume: 0.1,
    icon: "grand carton.png",
    quantity: 0,
  },
  {
    id: 234,
    category: "materiel_bricolage",
    name: "Cartons (petits) 34,5x27x30 cm",
    volume: 0.05,
    icon: "petit carton.png",
    quantity: 0,
  },
  {
    id: 235,
    category: "jardin",
    name: "Table jardin 8 pers. Ou +",
    volume: 1.5,
    icon: "table8.png",
    quantity: 0,
  },
  {
    id: 236,
    category: "jardin",
    name: "Table de jardin 6 pers.",
    volume: 1,
    icon: "table6.png",
    quantity: 0,
  },
  {
    id: 237,
    category: "jardin",
    name: "Table de jardin 4 pers.",
    volume: 0.5,
    icon: "table-ronde.png",
    quantity: 0,
  },
  {
    id: 238,
    category: "jardin",
    name: "Table de jardin pliante",
    volume: 0.35,
    icon: "table-pliable.png",
    quantity: 0,
  },
  {
    id: 239,
    category: "jardin",
    name: "Chaise",
    volume: 0.25,
    icon: "chaise (1).png",
    quantity: 0,
  },
  {
    id: 240,
    category: "jardin",
    name: "Chaise Longue",
    volume: 0.3,
    icon: "chaise-longue.png",
    quantity: 0,
  },
  {
    id: 241,
    category: "jardin",
    name: "Salon de jardin",
    volume: 2.5,
    icon: "table.png",
    quantity: 0,
  },
  {
    id: 242,
    category: "jardin",
    name: "Barbecue",
    volume: 0.25,
    icon: "barbecue.png",
    quantity: 0,
  },
  {
    id: 243,
    category: "jardin",
    name: "Transat",
    volume: 0.4,
    icon: "transat.png",
    quantity: 0,
  },
  {
    id: 244,
    category: "jardin",
    name: "Tonneau à vin",
    volume: 1,
    icon: "tonneau-de-vin.png",
    quantity: 0,
  },
  {
    id: 245,
    category: "jardin",
    name: "Parasol (avec pied)",
    volume: 0.2,
    icon: "parasol.png",
    quantity: 0,
  },
  {
    id: 246,
    category: "jardin",
    name: "Grosse poubelle",
    volume: 0.75,
    icon: "poubelle-de-recyclage.png",
    quantity: 0,
  }
   ]);

  const updateQuantity = (id: number, change: number) => {
    setItems(prev =>
      prev.map(item =>
        item.id === id ? { ...item, quantity: Math.max(0, item.quantity + change) } : item
      )
    );
  };

  const getTotalVolume = () =>
    items.reduce((total, item) => total + item.volume * item.quantity, 0).toFixed(2);

  const groupedItems = items.reduce<Record<string, FurnitureItem[]>>((acc, item) => {
    if (!acc[item.category]) acc[item.category] = [];
    acc[item.category].push(item);
    return acc;
  }, {});

  const handleContinueToQuote = () => {
    const selectedItems = items.filter(item => item.quantity > 0);
    navigate("/quote", { state: { volume: getTotalVolume(), items: selectedItems } });
  };

  return (
    <div className="min-h-screen">
      <Navbar />

      {/* Hero Section */}
      <section className="relative py-20 mt-20 bg-gradient-to-r from-primary to-secondary text-primary-foreground">
        <div className="container mx-auto px-4 text-center">
          <h1 className="text-4xl md:text-5xl font-bold mb-6 animate-fade-in">{t.heroTitle}</h1>
          <p className="text-xl max-w-2xl mx-auto animate-fade-in">{t.heroSubtitle}</p>
        </div>
      </section>

      {/* Calculator Section */}
      <section className="py-16">
        <div className="container mx-auto px-4 grid lg:grid-cols-3 gap-8">
          {/* Items Selection */}
          <div className="lg:col-span-2 space-y-6">
            {Object.entries(groupedItems).map(([category, categoryItems]) => (
              <Card key={category} className="border-border">
                <CardHeader>
                  <CardTitle className="text-2xl text-foreground">
                    {t.categories[category as keyof typeof t.categories] || category}
                  </CardTitle>
                </CardHeader>
                <CardContent className="max-h-[500px] overflow-y-auto space-y-2">
                  <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-2">
                    {categoryItems.map(item => (
                      <div
                        key={item.id}
                        className="flex flex-col items-center bg-muted p-2 rounded-lg hover:bg-muted/80 transition-colors"
                      >
                        <img src={item.icon} alt={item.name} className="h-10 w-10 object-contain mb-1" />
                        <span className="text-xs text-center font-medium">{item.name}</span>
                        <span className="text-[10px] text-muted-foreground">{item.volume} m³</span>
                        <div className="flex items-center gap-1 mt-1">
                          <Button
                            variant="outline"
                            size="icon"
                            onClick={() => updateQuantity(item.id, -1)}
                            disabled={item.quantity === 0}
                          >
                            <Minus className="h-3 w-3" />
                          </Button>
                          <span className="w-6 text-center text-sm font-medium">{item.quantity}</span>
                          <Button variant="outline" size="icon" onClick={() => updateQuantity(item.id, 1)}>
                            <Plus className="h-3 w-3" />
                          </Button>
                        </div>
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>

          {/* Summary Card */}
          <div className="lg:col-span-1">
            <Card className="sticky top-24 border-border bg-gradient-to-br from-primary/5 to-accent/5">
              <CardHeader>
                <CardTitle className="text-2xl text-foreground flex items-center gap-2">
                  <CalcIcon className="h-6 w-6 text-primary" />
                  {t.totalVolume}
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-6">
                <div className="text-center py-8">
                  <div className="text-6xl font-bold text-primary mb-2">{getTotalVolume()}</div>
                  <div className="text-2xl text-muted-foreground">m³</div>
                </div>

                <div className="space-y-2 text-sm text-muted-foreground max-h-[300px] overflow-y-auto">
                  {items
                    .filter(item => item.quantity > 0)
                    .map(item => (
                      <div key={item.id} className="flex justify-between">
                        <span>
                          {item.quantity}x {item.name}
                        </span>
                        <span className="font-medium">
                          {(item.volume * item.quantity).toFixed(2)} m³
                        </span>
                      </div>
                    ))}
                </div>

                {parseFloat(getTotalVolume()) > 0 && (
                  <Button variant="hero" size="lg" className="w-full" onClick={handleContinueToQuote}>
                    {t.continueButton}
                  </Button>
                )}

                <p className="text-xs text-muted-foreground text-center">{t.estimationNote}</p>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>

      <Footer />
    </div>
  );
};

export default Calculator;